CREATE TABLE [combined] (
  [fgc] VARCHAR (255),
  [tec] VARCHAR (255),
  [niin] VARCHAR (255),
  [wc_cd] VARCHAR (255),
  [mcn] VARCHAR (255) CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [cntl_mcn] VARCHAR (255),
  [cur_ti_ddsn] VARCHAR (255),
  [org_cd] VARCHAR (255),
  [cur_mgmt_cd] VARCHAR (255),
  [jcn] VARCHAR (255),
  [e_part_no] VARCHAR (255),
  [e_serno] VARCHAR (255),
  [se_part_no] VARCHAR (255),
  [buno_serno] VARCHAR (255),
  [sys_rsn] VARCHAR (255),
  [unit_price] CURRENCY,
  [net_price] CURRENCY,
  [maint_trans_cd] VARCHAR (255),
  [act_take_cd] VARCHAR (255),
  [A1_status] VARCHAR (255),
  [A1_date_text] VARCHAR (255),
  [A1_date] DATETIME,
  [initiated_date_text] VARCHAR (255),
  [initiated_date] DATETIME,
  [current_status] VARCHAR (255),
  [current_status_date_text] VARCHAR (255),
  [current_status_date] DATETIME,
  [ty_maf_cd] VARCHAR (255),
  [maint_lv_cd] VARCHAR (255),
  [wrk_pri_cd] VARCHAR (255),
  [proj_cd] VARCHAR (255),
  [Maf_age] LONG,
  [cost_key] VARCHAR (255),
  [eqp_sts_cd] VARCHAR (255)
)
