CREATE TABLE [Inventory] (
  [acct_qty] SHORT,
  [awp_qty] SHORT,
  [cncl_qty] SHORT,
  [cosal_faq] SHORT,
  [cosal_qty] SHORT,
  [depl_pkup_qty] SHORT,
  [difm_qty] SHORT,
  [dop_uic] VARCHAR (255),
  [due_qty] SHORT,
  [ei_qty] SHORT,
  [eriou_qty] SHORT,
  [exrp_qty] SHORT,
  [isser_qty] SHORT,
  [lis_qty] SHORT,
  [long_sup_ind] VARCHAR (255),
  [lpurp_faq] SHORT,
  [lpurp_pkup_oh] SHORT,
  [match_set_ind] VARCHAR (255),
  [mov_pri_dsg] SHORT,
  [niin] VARCHAR (255),
  [fgc] VARCHAR (255),
  [note_cd_1] VARCHAR (255),
  [note_cd_2] VARCHAR (255),
  [note_cd_3] VARCHAR (255),
  [note_cd_4] VARCHAR (255),
  [note_cd_5] VARCHAR (255),
  [note_cd_6] VARCHAR (255),
  [note_cd_7] VARCHAR (255),
  [note_cd_8] VARCHAR (255),
  [owe_qty] SHORT,
  [pool_cd] VARCHAR (255),
  [rfi_qty] SHORT,
  [so_iou_qty] SHORT,
  [ssp_qty] SHORT,
  [subcus_qty] SHORT,
  [trnrd_tm] SHORT,
  [uncd_note] VARCHAR (255),
  [wpurp_faq] SHORT
)
