CREATE TABLE [Requisitions] (
  [mcn] VARCHAR (50),
  [cage] VARCHAR (255),
  [cog] VARCHAR (255),
  [cur_mcn] VARCHAR (255),
  [cur_niin] VARCHAR (255),
  [ddsn] VARCHAR (255),
  [ddsn_suf] VARCHAR (255),
  [lsc] VARCHAR (255),
  [ord_qty] VARCHAR (255),
  [part_no] VARCHAR (255),
  [rep_mcn] VARCHAR (255),
  [wc_cd] VARCHAR (255),
  [nomen] VARCHAR (255),
  [ui] VARCHAR (255),
  [fgc] VARCHAR (255),
  [rep_itm_ind] VARCHAR (255),
  [buno_serno] VARCHAR (255),
  [cur_ti_ddsn] VARCHAR (255),
  [jcn] VARCHAR (255),
  [unit_price] CURRENCY,
  [net_price] CURRENCY,
  [ord_dttm_text] VARCHAR (255),
  [ord_dttm] DATETIME,
  [lsc_dttm_text] VARCHAR (255),
  [lsc_dttm] DATETIME
)
